---
deployment:
  tasks:
    - export DEPLOYPATH=/home/capsulecorp/public_html/
    - /build/cp -R static $DEPLOYPATH
    - /build/cp asset-manifest.json $DEPLOYPATH
    - /build/cp index.html $DEPLOYPATH
    - /build/cp favicon.ico $DEPLOYPATH
    - /build/cp logo.png $DEPLOYPATH
    - /build/cp logo192.png $DEPLOYPATH
    - /build/cp logo512.png $DEPLOYPATH
    - /build/cp manifest.json $DEPLOYPATH
    - /build/cp robots.txt $DEPLOYPATH